### ISSUE TITLE
change args + remove for reminders

### ISSUE THREAD

**Issue by ZeNyfh** [ZeNyfh/gigavibe-java-edition#108]
?reminder "add" is useless, we can get away with ?reminder <timestamp>

and for remove
?reminder remove <int> works, but it would be nice to list the reminders for the user and then ask them "are you sure? yes or no" (yes or no will be parsed as y[es], n[o])

**Comment by ZeNyfh** [comment]
confirmation is useless, it tells you the timestamp you removed if you do remove it so it can easily be re-added, i may just add a footer to the embed incase they wanna re-remind

**Comment by ZeNyfh** [comment]
@9382 
![image](https://user-images.githubusercontent.com/66276905/233355782-bedbdfa9-80ab-4fc1-983d-bf97e7584459.png)
unsure how to do this, i simply want to remove the need for the "add" argument as it isnt necessary for anything and causes some confusion for others.

**Comment by 9382** [comment]
I think I've ran into an issue before where discord doesnt like a mix of subcommands and not subcommands, meaning this may not be an option.
Will look into it when I can

**Comment by 9382** [comment]
![image](https://user-images.githubusercontent.com/49820045/233472678-f2b907b9-fa34-4779-96f6-f4a623c93ef8.png)
As suspected, this isn't possible. This leaves us with 2 choices
1) Just stick to doing `/reminder (add/remove/list)`
2) Remove subcommands entirely, and force the first parameter to be one of the 3 values (which is basically the same in practice anyways) (I'm not sure how this is done but I know another bot does it)
Not having `add` but having `remove` and `list` is not a choice here
