### ISSUE TITLE
add autoplay

### ISSUE THREAD

**Issue by ZeNyfh** [ZeNyfh/gigavibe-java-edition#110]
simply this feature but in the bot, plays similar songs/videos after the current song/video has finished
![image](https://user-images.githubusercontent.com/66276905/233806034-77afeb34-2c1c-4db5-8d3f-eb46bcf49426.png)

**Comment by 9382** [comment]
is this really a good idea?

**Comment by ZeNyfh** [comment]
> is this really a good idea?

I forgot to elaborate on this, it will be a setting similar to "loop" or "loopqueue"

**Comment by ZeNyfh** [comment]
I taught @T1G37 how to make commands and he is working on this.

**Comment by 9382** [comment]
For reference, 139cd29
