### ISSUE TITLE
Implement genius API for lyrics & song/artist info

### ISSUE THREAD

**Issue by ZeNyfh** [ZeNyfh/gigavibe-java-edition#112]
These are the things that can be implemented, in order of how much I care:

1. getting the lyrics of a song
2. getting the information about a song
3. getting the information about an artist
4. searching for a song by its lyrics

**Comment by garret1317** [comment]
alternatively, consider [musixmatch](https://www.musixmatch.com/)
from the brief look i had, their api seemed much nicer than genius's
i'm not even sure if the genius api even _has_ lyrics lmao

some of the lyrics/metadata on musixmatch are user generated, so it could be a bit dodgy in quality at times
but its used by spotify, so at least it won't be just the bot getting it wrong lol

these docs may be of interest:
https://developer.musixmatch.com/documentation/api-reference/matcher-track-get
https://developer.musixmatch.com/documentation/api-reference/matcher-lyrics-get
though i didn't look too deeply into them, they might not be what you need

**Comment by ZeNyfh** [comment]
Id like to work on this soon, however I do not know how I'd like to do this, messages could get very lengthy fast and text files could get annoying, any way to make this work nicer?

**Comment by ZeNyfh** [comment]
@garret1317 thank you for the great suggestion of not worrying about it, I will go for a message

**Comment by ZeNyfh** [comment]
musixmatch isn't an option here due to licensing issues and the free plan not working with what I need.

**Comment by ZeNyfh** [comment]
Changing again, I am switching to lrclib.net!
