### ISSUE TITLE
raw java.lang.String is stored in json

### ISSUE THREAD

**Issue by ZeNyfh** [ZeNyfh/gigavibe-java-edition#115]
i looked in a backup since an issue occurred, there's a raw java string object in there, this will need investigating

**Comment by ZeNyfh** [comment]
setting to critical as this is the cause of json files getting nulled

**Comment by 9382** [comment]
No luck on reproducing this so far - any more detail? Do you have the `backup_XYZ` in the backup folder as a reference?

**Comment by 9382** [comment]
Bumping priority down - still an issue, but no longer one that'll nullify configs after f0d2abf

**Comment by 9382** [comment]
See 770f6d6
