### ISSUE TITLE
Fix and Overhaul Insert

### ISSUE THREAD

**Issue by 9382** [ZeNyfh/gigavibe-java-edition#119]
Multiple issues:
* Lots of un-handled redtext capabilities. No check on the length of arguments means people have no feedback if they used it wrong
* No support for file inputs (as in uploading, sending the url works). Will redtext as it expects args[2] to exist always (see above).
* The hell is "Error from decoder 16388"? Thats a rather unhelpful message.

I really feel like we should just copy what we have in Play or something like that. Assigning to @ZeNyfh since this is your type of thing

**Comment by ZeNyfh** [comment]
the 1st 2 issues, yes thats fixable, the 3rd issue, that's actually in play command too, error 16388 is simply an error message for when a track does load but the decoder fails, I can add more context to that instead.

**Comment by ZeNyfh** [comment]
> In that case, dw too much about issue 3. Do we know if we've even had that trigger before?

Yes, though this was during the beginning phase of development, and I do not remember what caused it.

**Comment by ZeNyfh** [comment]
After a more thorough search, it seems as if this issue is not AAC or malformed audio data, it seems more likely to be something to do with m3u8 files (possibly lack of permission to connect to external server), which I believe is the original reason as to why I disallowed m3u8 files from being played as a file in ?play.

**Comment by ZeNyfh** [comment]
issue 1 and 2 sorted in https://github.com/ZeNyfh/gigavibe-java-edition/commit/0fee70d601a8d7002b9de55e54e3ae2e062d383f
"Error from decoder 16388" seems to be like an archaic error that hasn't occurred since.
