### ISSUE TITLE
Search for glue and spaghetti code (refactor)

### ISSUE THREAD

**Issue by ZeNyfh** [ZeNyfh/gigavibe-java-edition#123]
The title is what it literally is but I will actually search for specific things.

Bot leaving instead of retrying x times when playing a track (people saying "bot broken" to some tracks in playlists).

Look for old code that was implemented to fix a bug that could be conflicting with something else now (for example I strongly believe there is code in Main and PlayerManager which is almost the same)

I will tag this comment if I find more however I will focus on the main examples above.

**Comment by 9382** [comment]
> old code that was implemented to fix a bug that could be conflicting with something else now

That describes #105 quite well

**Comment by ZeNyfh** [comment]
some glue/spaghetti code that was recently removed was the reply with "." code in playermanager.
I still do not know what else I should do with this issue, I will close it as it doesn't really have a purpose as #105 exists and code refactors happen naturally.
