### ISSUE TITLE
Write a Log file for printlnTime and errors

### ISSUE THREAD

**Issue by 9382** [ZeNyfh/gigavibe-java-edition#128]
So we can look back on an easy to search format to look at potential rare errors and what text they produced, since rn I'm fairly certain the only "logging" is directly in the console, so if that closes or prints too much its basically useless

**Comment by ZeNyfh** [comment]
Alternative solution, `bot.jar >> output.txt`. Command line tools exist, unneeded feature. Just append onto that one big file constantly, will show past and present like a Minecraft server output does.

**Comment by 9382** [comment]
Doesnt this prevent standard console output? Or am I misremembering

**Comment by ZeNyfh** [comment]
This does prevent standard console output, I guess it could be worth looking into.
