### ISSUE TITLE
Add audio filter support (speed, pitch, etc)

### ISSUE THREAD

**Issue by ZeNyfh** [ZeNyfh/gigavibe-java-edition#131]
There is issue #47 however that was very broad and included more than just audio filters, making this its own issue.

These 2 features are a priority, however this is not an extensive list, more features may come from this.
- speed
- pitch

**Comment by ZeNyfh** [comment]
set to priority high as this has been requested by users.

**Comment by ZeNyfh** [comment]
I am working on this (while at college on a vpn) and I have it working in a test environment, all I need to do is move the logic into commands and this will *finally* be a feature.

**Comment by 9382** [comment]
bugs to figure out, keeping this open until resolved

**Comment by garret1317** [comment]
:neck

**Comment by 9382** [comment]
Update: It seems the filters don't like working together, and one of the filters (which to be specific is random) will not work while the other will. E.g. pitch doesnt work but vibrato does, restart instance, pitch works and vibrato doesn't. Very bizarre behaviour, will need to figure this out

**Comment by 9382** [comment]
Both filters now correctly apply. Beyond some cleanup of how we want to access filters, this is pretty much complete

**Comment by ZeNyfh** [comment]
fixed in https://github.com/ZeNyfh/gigavibe-java-edition/commit/6b8434a6fda132bfd235f43b2f1a1c740498e612
