### ISSUE TITLE
Whatever this is

### ISSUE THREAD

**Issue by 9382** [ZeNyfh/gigavibe-java-edition#132]
I swear I've reported this like 5 times man
![image](https://github.com/ZeNyfh/gigavibe-java-edition/assets/49820045/17c03336-6cb6-4fa3-b027-a8ba8a12a7c7)

**Comment by ZeNyfh** [comment]
I swear I've fixed this like 5 times man

**Comment by MouldyPizzaMuncher** [comment]
WHAT THE FUCK IS THIS?
