### ISSUE TITLE
Improve slash command behaviour of ?play

### ISSUE THREAD

**Issue by 9382** [ZeNyfh/gigavibe-java-edition#133]
With the move somewhat away from text-based commands, we should probably make the play command better supported for slash commands. I specifically mean avoiding immediately replying and deleting it and then sending a response in an unrelated later message, since this hides who used the command and with what arguments, and also can fill logs that track message deletion

**Comment by ZeNyfh** [comment]
Yes, I remember you mentioning this
I think looking into replying with "." and then editing that message would be a better approach.
