### ISSUE TITLE
Insert command voids songs in the queue and doesnt insert at the right index

### ISSUE THREAD

**Issue by 9382** [ZeNyfh/gigavibe-java-edition#141]
![image](https://github.com/ZeNyfh/gigavibe-java-edition/assets/49820045/0accf235-20af-46ab-a4e8-972d9a0948e5)

**Comment by ZeNyfh** [comment]
I have implemented a fix, however I cannot test it due to my current whereabouts, I will keep this issue open until I can test it.

Added the help wanted label to this as it seemed like the most fitting label for something like this.
