### ISSUE TITLE
Potential better handling method for slash commands

### ISSUE THREAD

**Issue by 9382** [ZeNyfh/gigavibe-java-edition#143]
Currently, looking at UpdateSlashCommands and other stuff, we call updateCommands on every guild specifically rather than doing it under the bot in general. This feels like excessive extra leg work and I'm not sure what this entails for the first time a bot joins a new server. We should really think about swapping to doing it under the bot instead (its just as simple and probably more efficient, plus it would force apply every reboot)
@ZeNyfh Is there any reason this is done specifically under every guild instead of as a bot in general?

**Comment by ZeNyfh** [comment]
Implement this and lets see what happens.
Keep in mind that both systems will apply therefore "updateslash" may have to be temporarily updated to remove all existing commands in every guild.

**Comment by 9382** [comment]
Implemented. Close this issue once you update the bot and run /removeslash

**Comment by ZeNyfh** [comment]
I have done the deed.
