### ISSUE TITLE
Fix and rework autoplay 

### ISSUE THREAD

**Issue by ZeNyfh** [ZeNyfh/gigavibe-java-edition#148]
I don't even know how to describe this but you can basically do insert 1 by doing autoplay like this:
![image](https://github.com/ZeNyfh/gigavibe-java-edition/assets/66276905/62afd484-f56a-406d-baa6-6420058d3ec8)
![image](https://github.com/ZeNyfh/gigavibe-java-edition/assets/66276905/48683ca8-56c3-454a-8c44-858d01ea9023)

Autoplay also ONLY works for youtube, not for anything else.

**Comment by 9382** [comment]
Bonus issue: this is bad reply behaviour for slash commands when exiting autoplay
![image](https://github.com/ZeNyfh/gigavibe-java-edition/assets/49820045/16defa47-58e5-495c-a0e8-e12665b20004)

**Comment by ZeNyfh** [comment]
Things to do:
- add a system to disallow autoplay from queuing the same track in the current autoplay session. (removal of 1/3 chance thing) 
- add support for SoundCloud and Spotify autoplay
- fix bad slash command behaviour (merge messages or send message to the channel instead)
- fix whatever that "insert 1" bug is
- change how the autoplay logic works (integration with last.fm API)
