### ISSUE TITLE
Actively dispose of temporary files

### ISSUE THREAD

**Issue by 9382** [ZeNyfh/gigavibe-java-edition#149]
Recently changed the file system to avoid dangerous calls to Thread.sleep by using a dedicated temp/ directory and clearing it on restart, but this now means we form an (admittedly minor) build-up of files until what will hopefully be the next update. Something to actively clear these temporary files after a minute or few of existing would be nice, but by no means hugely important.

**Comment by ZeNyfh** [comment]
This is a very simply fix, I can do this now.
