### ISSUE TITLE
Logger/stdout arent ordered correctly sometimes.

### ISSUE THREAD

**Issue by ZeNyfh** [ZeNyfh/gigavibe-java-edition#154]
**Describe the bug**
Looking at the times in the console, they seem to be not in the correct order.

**Expected behavior**
The outputs in the console should be in the correct order.

**Screenshots**
![image](https://github.com/ZeNyfh/gigavibe-java-edition/assets/66276905/392cb311-3bc0-4403-91cd-0060f9c51560)

**Comment by ZeNyfh** [comment]
Added backlog label as this really isn't important, i believe this only occurs when nothing has been logged for a while.
If you wish to fix it, be my guest.
This is the commit that caused this bug: https://github.com/ZeNyfh/gigavibe-java-edition/commit/fa93d25aef0241addcd0be790a617e64744dc28c

**Comment by 9382** [comment]
The changes I made to the logger in 6a80b37 remove some weird gymnastics that used to happen with getting the stream out; this could've inadvertently fixed the bug, but we don't have a consistent error case to know that for sure. Just keep this in mind if you're looking for the bug using this commit onwards

**Comment by 9382** [comment]
Stared at that screenshot a little closer

and uh

the first print is from the 23rd
and the second print is from the 24th

we are both stupid
