### ISSUE TITLE
Log errors aren't perfectly timestamp formatted

### ISSUE THREAD

**Issue by 9382** [ZeNyfh/gigavibe-java-edition#158]
Since the logs are done at a timer rate of 1 second, if multiple error messages are emitted during that second, only the first one actually has a timestamp attached to it since the entire buffer gets dumped at once. Ideally, a call to .print or .println the stream should either immediately add the timestamp there and then *or* immediately cause a file write, whichever is doable (and ideally the first since then its theoretically a few less file operations)
![image](https://github.com/ZeNyfh/gigavibe-java-edition/assets/49820045/6d3e683a-ba67-4d4c-8c73-074f251ee283)

**Comment by ZeNyfh** [comment]
@9382 said he'd look into this.
The reason why I am commenting this is that I believe that a release can be made after this commit is done.

**Comment by 9382** [comment]
Solved by burning the entire existing system to the ground and remaking it
