### ISSUE TITLE
The play command can cause a concurrent modification exception

### ISSUE THREAD

**Issue by ZeNyfh** [ZeNyfh/gigavibe-java-edition#172]
when accessing the queue, it can cause an exception (this has happened in production once, maybe more idk i didnt check thoroughly)
a synchronized method should handle this, I've talked with @9382 about this somewhat but it needs a followup. 
This may also tie somewhat into #170.

**Comment by 9382** [comment]
correction: its already locked
![image](https://github.com/user-attachments/assets/29b4ea36-7ee4-412c-a3c2-de30c09d1f64)
maybe something else in play? (Do we loop the queue and have the ability for it to be modified at the same time?)

**Comment by ZeNyfh** [comment]
Ive looked into it just in case, but it does seem like its totally fine. I was blind the other day and just read the console output incorrectly.
