### ISSUE TITLE
Localise files

### ISSUE THREAD

**Issue by ZeNyfh** [ZeNyfh/gigavibe-java-edition#187]
- [x] CommandAutoplay
- [x] CommandBlockChannel
- [x] CommandBug
- [x] CommandClearQueue
> NA CommandDevTests
- [x] CommandDisconnect
- [x] CommandDJ
> NA CommandExport
- [x] CommandForceSkip
> NA CommandGetDump
- [x] CommandGithub
- [x] CommandHelp
- [x] CommandInfo
- [x] CommandInsert
- [x] CommandInvite
- [x] CommandJoin
- [x] CommandLocale
- [x] CommandLoop
- [x] CommandLoopQueue
- [x] CommandLyrics
- [x] CommandNowPlaying
- [x] CommandPause
- [x] CommandPing
- [x] CommandPitch
- [x] CommandPlay
- [x] CommandPrivacyPolicy
- [x] CommandQueue
- [x] CommandRadio
- [x] CommandRemove
> NA CommandReplyToMessage
- [x] CommandSeek
> NA CommandSendLogs
> NA CommandSendUsage
- [x] CommandShuffle
- [x] CommandSkip
- [x] CommandSpeed
- [x] CommandTOS
- [x] CommandVibrato
- [x] CommandVolume
- [x] BaseCommand
- [x] CommandStateChecker
- [x] PlayerManager
- [x] TrackScheduler
- [x] Main

**Comment by ZeNyfh** [comment]
I need sleep, there are a few more pieces of text that need localising which i did not catch with my regex (these are not in any reply embed)

one of these can be found in main on line 736: "An update to the bot occurred, your queue and parameters have been restored!\n-# If you wish to see what changed, feel free to join the support server found in the bot's about me."

Another issue is to do with createQuickError and how it does not work with the current system as theres no way to get what guild called that function without changing every function call to include the guild ID, @9382 if you could suggest something that would be nice, i have a slight idea in mind but i could be going insane:
pass the original error function output to a post-processor which is fired on any CommandEvent, so that defining the "Error" string to event.getLang("Main.error")

**Comment by 9382** [comment]
First idea that comes to mind is making it a function of the event itself in one way or another (e.g. `event.createQuickError` or `event.replyQuickError`)

**Comment by ZeNyfh** [comment]
After finally settling into uni...
That is a good suggestion, however another edge case has come up. This being the HandleButtonEvent in CommandQueue.
I will make your comment an issue to address as that is a nicer implementation than the current one.

**Comment by ZeNyfh** [comment]
there is: guildLocales.get(event.getGuild().getIdLong()).get("...")
however there needs to be a cleaner implementation, I will leave this as a TODO next to the first instance of this.
