### ISSUE TITLE
&Song duration breaks formatting when the time is broken

### ISSUE THREAD

**Issue by 9382** [ZeNyfh/gigavibe-java-edition#34]
When using a video with a broken formatting time (E.g. https://cdn.discordapp.com/attachments/959513178096668712/972222090176499793/ML_anime.webm) it causes the duration to show as `` during the quick summary. Also, if it has the chance to, it breaks the formatting in &np
![image](https://user-images.githubusercontent.com/49820045/167206890-87cb106a-7f8e-4fc5-97f5-f6d123f95bba.png)

**Comment by ZeNyfh** [comment]
is this closeable? #29 was fixed but im unsure about the now playing part of this, will need more info on this @9382

**Comment by 9382** [comment]
Cant get the NP side to trigger recently, probably safe to close
