### ISSUE TITLE
add caption command

### ISSUE THREAD

**Issue by bullpoo1234** [ZeNyfh/gigavibe-java-edition#42]
!caption captions image with a font and white thing above image
!esmcaption caption but with esm font

**Comment by ZeNyfh** [comment]
i would like to revisit this

**Comment by garret1317** [comment]
`ffmpeg -i in.png  -filter_complex "[0:v]pad=iw:ih+50:0:50:color=white,drawtext=text='your text here':fontfile=/path/to/font.ttf:fontsize=24:x=(w-tw)/2:y=(50-th)/2" out.png` sounds like it does what you want
adapted from https://stackoverflow.com/a/33287276
[pad filter docs](https://ffmpeg.org/ffmpeg-filters.html#pad)
[drawtext filter docs](https://ffmpeg.org/ffmpeg-filters.html#drawtext)
hopefully those give some idea of what it's doing

example
![it_knows](https://user-images.githubusercontent.com/76261416/177035633-3f7ff37f-9635-4441-981a-21c62aac48da.png)

won't automatically linebreak or add more white if the text is too long, so be aware of that
may or may not be better/easier with imagemagick, but i don't know how you'd go about doing it
