### ISSUE TITLE
!compress command

### ISSUE THREAD

**Issue by bullpoo1234** [ZeNyfh/gigavibe-java-edition#44]
!compress uses a compression algorithm to compress video/image

**Comment by ZeNyfh** [comment]
may consider this as not everyone has storage and people may want to download smaller files.

**Comment by ZeNyfh** [comment]
> may consider this as not everyone has storage and people may want to download smaller files.

Stupid reason to consider this request. this will not be added, though a low bitrate audio filter may be considered for the audioplayer.
