### ISSUE TITLE
miscellaneous  captioning commands

### ISSUE THREAD

**Issue by bullpoo1234** [ZeNyfh/gigavibe-java-edition#45]
Commands to caption media.
Run $help command for more information on a command.
$bottomcaption
Captions underneath media.
$breakingnews
Create a fake "Breaking News" screencap.
$caption
Captions media.
$eminem
Eminem says something below your media.
$esmcaption
Captions media in the style of Essem's esmBot.
$freezemotivate
Ends video with a freeze frame from $motivate.
$freezemotivateaudio
Ends video with a freeze frame from $motivate with custom audio.
$meme
Captions media in the style of top text + bottom text memes.
$motivate
Captions media in the style of demotivational posters.
$petergriffin
Peter Griffin says something below your media.
$snapchatcaption
Captions media in the style of the classic Snapchat caption.
$stuff
Captions media in the style of the "i'm stuff" meme
$stuffstretch
Alternate version of $stuff where RDJ stretches
$tenorcap
Captions media in the style of tenor.
$twittercaption
Captions media in the style of a Twitter screenshot.
$twittercaptiondark
Captions media in the style of a dark mode Twitter screenshot.
$whispercaption
Captions media in the style of the confession website Whisper.

**Comment by ZeNyfh** [comment]
music focused
