### ISSUE TITLE
convert video to audio and vice versa

### ISSUE THREAD

**Issue by bullpoo1234** [ZeNyfh/gigavibe-java-edition#46]
toaudio - Converts a video to only audio.
tovideo - Converts audio to only video (black bg).

**Comment by ZeNyfh** [comment]
rename - yes
spoiler - are people handicapped? (no)
tenorgif - no, either hold on the embed on mobile or right click on desktop
toapng - seems redundant, maybe
toaudio - maybe
togif - maybe
topng - ???
tovideo - gif to video and/or audio to video, perhaps
