### ISSUE TITLE
misc editing commands

### ISSUE THREAD

**Issue by bullpoo1234** [ZeNyfh/gigavibe-java-edition#47]
$add
Adds the pixel values of the second video to the first.
$addaudio
Adds audio to media.
$autotune
Autotunes media.
$compressv
Makes videos terrible quality.
$concatv
Makes one video file play right after another.
$corrupt
Intentionally glitches media
$deepfry
Applies several filters to the input media to make it appear "deep fried" in the style of deep fried memes.
$fps
Changes the FPS of media.
$gifloop
Changes the amount of times a gif loops
$hstack
Stacks 2 videos horizontally
$hue
Change the hue of media.
$invert
Inverts colors of media
$jpeg
Makes media into a low quality jpeg
$magick
Apply imagemagick's liquid/content aware scale to an image.
$mute
alias for $volume 0
$overlay
Overlays the second input over the first
$pitch
Changes pitch of audio
$random
Shuffles the frames of a video around.
$reencode
Re-encodes media.
$repost
Reposts media as-is.
$resize
Resizes an image.
$reverse
Reverses media.
$rotate
Rotates and/or flips media
$roundcorners
Round corners of media
$speed
Changes the speed of media.

**Comment by ZeNyfh** [comment]
add - no
addaudio - maybe
autotune - no
compressv - funny ffmpeg go brrr, yes
concatv - no
corrupt - no
deepfry - no
fps - no
gifloop - no
hstack - no
hue - no
invert - no
jpeg - no
magick - no
mute - no
pitch - no
random - no
reencode - no
repost - no
resize - no
reverse - no
rotate - no
roundcorners - no
speed - maybe

**Comment by ZeNyfh** [comment]
not looking for video/image editing yet.
