### ISSUE TITLE
Poor implementation of number detection

### ISSUE THREAD

**Issue by 9382** [ZeNyfh/gigavibe-java-edition#67]
The regex in CommandRemove (^[0-9]) only minimally checks the input and should be improved, as non integers will still pass this check

**Comment by ZeNyfh** [comment]
Feel free to do this, I wont be coding for the next few hours.

**Comment by ZeNyfh** [comment]
@9382 does this still need to be addressed?

**Comment by 9382** [comment]
Looking through the commits, I dont see any change particularly related to it, but I'll have to look into the current implementations again to really confirm that

**Comment by 9382** [comment]
a4f0479 should be the fix for that, im considering this good to close
