### ISSUE TITLE
Videodl doesnt work properly on linux

### ISSUE THREAD

**Issue by ZeNyfh** [ZeNyfh/gigavibe-java-edition#78]
This is due to the recent filter change

**Comment by ZeNyfh** [comment]
VideoDL on linux, doesn't work when formatted like this
![image](https://user-images.githubusercontent.com/66276905/194186929-97d18c66-ba27-4c63-9be9-8830fae81108.png)

While on the other hand, AudioDL does work when formatted similarly
![image](https://user-images.githubusercontent.com/66276905/194187013-e98f64a9-89df-4de7-8524-504553ac47a8.png)

VideoDL on linux does work when formatted like this though
![image](https://user-images.githubusercontent.com/66276905/194187119-34b0cd94-e0de-4a5e-b810-47a08532050e.png)

While on windows, the formatting is the same and it works perfectly, I have tried with \\ and \\\\ but to no avail, help would be appreciated.

**Comment by 9382** [comment]
It turns out the issue could lie in some improperly set-up modules, and isn't a code issue at its core. I've done some minor changes regardless, but I'm waiting for more information
