### ISSUE TITLE
Add playlist support to videodl/audiodl

### ISSUE THREAD

**Issue by ZeNyfh** [ZeNyfh/gigavibe-java-edition#82]
This will work exactly like how the current audiodl and videodl stuff works, just that it will send all the files to the user's dms instead to not flood the server. (This will be ALOT better once discord releases that 25mb upload limit for free users)

Once the process finishes, I may be able to just just do something with YT-DLP args and make the filename something like `UNIXMS(0).ogg`, and then i could iterate through all files in the directory that contain "UNIXMS" and send them to the user.
Though this will DEFINITELY need to be limited because of filesize stuff.

**Comment by 9382** [comment]
My idea for how this could work is that, if we know a playlist is involved (this is probably a yt-dlp thing), we download it all to a temporary subfolder, meaning naming issues are non-existant (YT-DLP will never conflict), and we just grab all subfiles
