### ISSUE TITLE
voteskip half worky

### ISSUE THREAD

**Issue by ZeNyfh** [ZeNyfh/gigavibe-java-edition#89]
I believe somewhere the skip count for the guild is reset when it isnt supposed to, @9382 or I will review this, depends who decides to do it first.

**Comment by 9382** [comment]
Note that, as far as my memory goes, this bug only manifests when 3 or more votes are required to skip

**Comment by ZeNyfh** [comment]
@9382 is this still relevant or does it require more investigation?
(could possibly get one of the Hell™ members to look at it, another pair of eyes may be good)

**Comment by 9382** [comment]
I don't know, as Ive said it requires 3+ people at once minimum to test and I don't have that. The code for it hasnt changed since, so the same comments from above still apply

**Comment by 9382** [comment]
Tested recently, no issue found. Closing this as fixed/cantreplicate
