### ISSUE TITLE
Add slash command support

### ISSUE THREAD

**Issue by ZeNyfh** [ZeNyfh/gigavibe-java-edition#90]
**This does not mean that I am switching to slash commands.**
Slash commands are entirely optional and are only getting implemented as they may help a small majority of people to use the bot (there are people nowadays which dont know about bots that dont use slash commands)

This shouldn't be too hard to implement either as upon the registering of commands, I can use the existing descriptions and command names to register slash commands or "application commands" as discord calls them.

**Comment by ZeNyfh** [comment]
oh this is LOVELY


### Slash Command Compatibility
- [ ] CommandAudioDL
- [ ] CommandBlockChannel
- [ ] CommandBotInfo
- [ ] CommandBug
- [ ] CommandClearQueue
- [ ] CommandDisconnect
- [ ] CommandDJ
- [ ] CommandForceSkip
- [ ] CommandGithub
- [ ] CommandHelp
- [ ] CommandInsert
- [ ] CommandInvite
- [ ] CommandJoin
- [ ] CommandLocalPlay
- [ ] CommandLoop
- [ ] CommandLoopQueue
- [ ] CommandNowPlaying
- [ ] CommandPing
- [ ] CommandPlay
- [ ] CommandQueue
- [ ] CommandRadio
- [ ] CommandRemove
- [ ] CommandSeek
- [ ] CommandSendAnnouncement
- [ ] CommandShuffle
- [ ] CommandSkip
- [ ] CommandVideoDL
- [ ] CommandVolume

**Comment by ZeNyfh** [comment]
there is currently no elegant solution for things like arguments (options as discord calls it), so this may need to be put on hold, however everything else can be basically copy and pasted and adapted to work with slash commands.

as of now, only CommandPing has been confirmed to work in slash commands

**Comment by 9382** [comment]
Slash commands are now by-default supported since 147055f, but some are imperfect or don't use the features they should (or possibly outright dont work as a slash command). Tracking list should be used to track what has and hasn't been confirmed to work, but progress has been made
