### ISSUE TITLE
split commands from jar into separate classpath (allow for hotswapping command classes)

### ISSUE THREAD

**Issue by ZeNyfh** [ZeNyfh/gigavibe-java-edition#92]
ok so, I dont know if this idea is even feasable, however if it is feasable, this would allow for updates to existing commands and the ability to add more commands while the bot is still running.

All that would need to be done is a command like "?reload" which would re-register all commands as the command registration system currently grabs command classes from an existing jar file which could be easily switched for a newer version, however the building process would become nightmarish if I were to do something like this and at worse, it would require maybe a few changes on the backend. But updating the bot would be so much easier.

**Comment by ZeNyfh** [comment]
changed the issue name, i can place the command classes in a directory and have the main class just loop through the classpath like it currently does for it to register them.

I will need to remember to edit the classpath in manifest.mf for this to work properly.

**Comment by ZeNyfh** [comment]
On hold until it actually becomes an issue (I will live without it for now)

**Comment by 9382** [comment]
removing "on hold" as innacurate tag - no comment on the actual issue

**Comment by ZeNyfh** [comment]
so, this would be *easy-ish* to implement, however editing the code after the fact in intellij would be painful, this will be a pain.

**Comment by ZeNyfh** [comment]
In hindsight, this was really not a good approach, it sounds like it is asking to cause issues, a better alternative for the problem I had here is to have jar file in an "update/" directory and simply stop the thread when the bot is in 0 vcs and there is a file in "update/", then just move the file from "update/" to the main directory and go from there, though half of this sounds like it would be run from a .bat / .sh script.
