### ISSUE TITLE
Make commands work in all guild channel types

### ISSUE THREAD

**Issue by ZeNyfh** [ZeNyfh/gigavibe-java-edition#94]
Will need to do some dumb conversion or make a custom function for this where it just try - catches a few times

**Comment by ZeNyfh** [comment]
technically this is a bug but this can also be called an enhancement if you wanna be optimistic about it

**Comment by 9382** [comment]
If required, I can work similar magic on it as I did with the slash command universal support

**Comment by 9382** [comment]
Status tracker
Commands currently work in:
- [x] Text channels
- [x] Voice text channels
- [x] Text thread channels
- [ ] Forum thread channels

Considering that everything except forum thread channels have now been fixed, I'm bumping the priority of this way down and the difficulty up (Forum thread channels' issue is different from the rest - some sort of poor grabbing that I'm not even sure is *our* fault, but who knows)

**Comment by 9382** [comment]
Note: Lines 249-253 include some very weird channel logic. Findind a way around that problem would be a lovely fix on top of everything else here

**Comment by 9382** [comment]
It appears Forum thread channels just work now, out of nowhere. I wonder if this was due to us bumping our JDA version (347da51?). Either way, I've fixed the only remaining case of weird channel behaviour (See 555e1c2), and this is now complete
