### ISSUE TITLE
THERE IS NO PERMISSION CHECK IN COMMANDDJ

### ISSUE THREAD

**Issue by ZeNyfh** [ZeNyfh/gigavibe-java-edition#96]
EVERYONE CAN GIVE/REMOVE DJ AAAAAAAAAAAAAAAA

**Comment by 9382** [comment]
Literally about to shower, but I could address this after. @ZeNyfh where the hell did the old code go? Swear we already had a check at some point

**Comment by 9382** [comment]
I think 7df3722 is to blame - the permission check for `MESSAGE_MANAGE` just gets entirely removed.
On a seperate note, looking at that commit, that check never existed for the `remove` option, only the `add` option. If thats the case, then yikes
