### ISSUE TITLE
Add video to audio sources downloaded using videodl 

### ISSUE THREAD

**Issue by ZeNyfh** [ZeNyfh/gigavibe-java-edition#99]
basically just a check with ffprobe to see if the file has a video stream and if it doesnt, make it have a 480p 1k 1fps video and then resize it

**Comment by 9382** [comment]
It does indeed convert it into an mp4 now, but since there's no video track, it doesn't embed in discord

**Comment by ZeNyfh** [comment]
This feature is deprecated and will not be worked on.
